/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cfe;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Admin;
import model.AdminDao;

/**
 *
 * @author Admin
 */
public class SignUpFrame extends javax.swing.JFrame {

    /**
     * Creates new form SignUpFrame
     */
    AdminDao dao = new AdminDao();
    int xx, xy;

    public SignUpFrame() {
        initComponents();
        tfID.setText(String.valueOf(dao.getMaxRowAdminTable()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnSignUp = new javax.swing.JPanel();
        lbExit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfAnswer = new javax.swing.JTextField();
        cbbQuestion = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        tfPassword = new javax.swing.JPasswordField();
        lbHide = new javax.swing.JLabel();
        lbShow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnSignUp.setBackground(new java.awt.Color(158, 111, 78));
        pnSignUp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnSignUpMouseDragged(evt);
            }
        });
        pnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnSignUpMousePressed(evt);
            }
        });
        pnSignUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbExit.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        lbExit.setForeground(new java.awt.Color(255, 255, 255));
        lbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbExit.setText("X");
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
        });
        pnSignUp.add(lbExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 24, 27));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up");
        pnSignUp.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 39, 371, -1));

        tfID.setBackground(new java.awt.Color(204, 204, 204));
        tfID.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        pnSignUp.add(tfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 110, 310, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID :");
        pnSignUp.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 84, 310, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username :");
        pnSignUp.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 156, 333, -1));

        tfUsername.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfUsernameKeyTyped(evt);
            }
        });
        pnSignUp.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 182, 310, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Security Question :");
        pnSignUp.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 300, 333, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password :");
        pnSignUp.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 228, 333, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Answer :");
        pnSignUp.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 372, 333, -1));

        tfAnswer.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        pnSignUp.add(tfAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 398, 310, 40));

        cbbQuestion.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cbbQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your favorite color?", "What is your family name?", "What is your first school name?", "What is your pet name?", "What was your first car?" }));
        cbbQuestion.setSelectedIndex(-1);
        pnSignUp.add(cbbQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 326, 310, 40));

        btnSave.setBackground(new java.awt.Color(237, 226, 219));
        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnSignUp.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 130, 36));

        btnBack.setBackground(new java.awt.Color(237, 226, 219));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnSignUp.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 130, 36));

        tfPassword.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        pnSignUp.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 254, 310, 40));

        lbHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hide.png"))); // NOI18N
        lbHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbHideMouseClicked(evt);
            }
        });
        pnSignUp.add(lbHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 30, 40));

        lbShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/visible.png"))); // NOI18N
        lbShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbShowMouseClicked(evt);
            }
        });
        pnSignUp.add(lbShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        setVisible(false);
    }//GEN-LAST:event_lbExitMouseClicked

    private void lbHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHideMouseClicked
        tfPassword.setEchoChar((char) 0);
        lbHide.setVisible(false);
        lbShow.setVisible(true);
    }//GEN-LAST:event_lbHideMouseClicked

    private void lbShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbShowMouseClicked
        tfPassword.setEchoChar('*');
        lbHide.setVisible(true);
        lbShow.setVisible(false);
    }//GEN-LAST:event_lbShowMouseClicked

    private void pnSignUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnSignUpMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnSignUpMousePressed

    private void pnSignUpMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnSignUpMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_pnSignUpMouseDragged

    private void tfUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUsernameKeyTyped
        char input = evt.getKeyChar();
        if (!(input < '0' || input > '9') && input != '\b') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Username doesn't contain any number!", "Warning", 2);
        }
    }//GEN-LAST:event_tfUsernameKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.1; i < 1.0; i += 0.1) {
            String s = "" + i;
            float f = Float.parseFloat(s);
            this.setOpacity(f);

            try {
                Thread.sleep(40);

            } catch (InterruptedException ex) {
                Logger.getLogger(SignUpFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (isEmpty()) {
            String username = tfUsername.getText().trim();
            if (!dao.isAdminNameExist(username)) {
                Admin admin = new Admin();
                admin.setId(dao.getMaxRowAdminTable());
                admin.setUsername(username);
                admin.setPassword(String.valueOf(tfPassword.getPassword()));
                admin.setsQues(cbbQuestion.getSelectedItem().toString());
                admin.setAns(tfAnswer.getText().trim());

                if (dao.insert(admin)) {
                    JOptionPane.showMessageDialog(this, "Admin Successfully Created..");
                    new LoginJFrame().setVisible(true);
                    setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Failed!!", "Warning", 2);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Username already exist..", "Warning", 2);
                
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new LoginJFrame().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    public boolean isEmpty() {
        if (tfUsername.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username is required", "Warning", 2);
            return false;
        }
        if (String.valueOf(tfPassword.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password is required", "Warning", 2);
            return false;
        }
        if (cbbQuestion.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Security question is required", "Warning", 2);
            return false;
        }
        if (tfAnswer.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Answer is required", "Warning", 2);
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbbQuestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbHide;
    private javax.swing.JLabel lbShow;
    private javax.swing.JPanel pnSignUp;
    private javax.swing.JTextField tfAnswer;
    private javax.swing.JTextField tfID;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
